POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBldHJpMTgwNyIsImlkIjoiNjA3NmIzZjEzMzY3ZmM1NzM4MGVlNDUyIiwiaWF0IjoxNjE4NDAwNjUxLCJleHAiOjE2MTg0MDQyNTF9.X1ovkcTWOTgE3KntsNXhJzhES7D3NhxcOgd5JhE0ix8

{
  "title": "Maximally optimizing image loading for the web in 2021",
  "author": "Some guy",
  "url": "https://www.industrialempathy.com/posts/image-optimizations/",
  "likes": 1,
  "userId": "6076b3f13367fc57380ee452"
}