DELETE http://localhost:3003/api/blogs/6076ee53e629293168472d97
Authorization: bear 

# STEPS TO TEST
# 1. Log in from ../login/login.rest with credentials petri1807/salasana
# 2. Copy Authorization token
# 3. Paste token after bear and save
# 4. Send request